### ISSUE TITLE
Provide complete documentation using docvim

### ISSUE THREAD

**Issue by lencioni** [wincent/pinnacle#1]
The readme only really says that this plugin

>  provides functions for manipulating `:highlight` groups.

Why should I care? How is this going to make my life better? Sell me on it!

**Comment by wincent** [comment]
I have a bit of a circular dependency thing going on here.

- Didn't want to make a real README until I had [Docvim](https://github.com/wincent/docvim) finished.
- In order to finish Docvim, needed Vim syntax highlighting for Docvim comments, hence [vim-docvim](https://github.com/wincent/vim-docvim) (and that one doesn't even have a README at all yet, for the same reason).
- vim-docvim depends on functionality that only existed in my dotfiles, so I extracted it into Pinnacle.

So, in good time you will get a real README with more details. Docvim itself is probably far from being finished, but funnily enough it's not far from being able to produce Markdown from Vim source code; in fact, it can already (for example, you can see how [this VimL source file](https://github.com/wincent/docvim/blob/master/tests/fixtures/markdown/integration-ferret-plugin.vim) in the integration test suite gets transformed into [this Markdown output](https://github.com/wincent/docvim/blob/master/tests/fixtures/markdown/integration-ferret-plugin.golden)), it's just there are a bunch of small-but-probably-tricky-to-implement details that I want to deal with.

This plug-in won't change your life, but it does make it easy to create italic and boldface elements of existing highlight groups. I used this in my dotfiles to make my statusline awesomer, and in vim-docvim I use it to make Docvim comments stand out.

**Comment by wincent** [comment]
Forgot to close this, but have been using docvim to generate the help for a while now. Most recently, 8 minutes ago. 😂
